### ISSUE TITLE
Toggle in Navbar

### ISSUE THREAD

**Issue by Shalini469717** [Shalini469717/TinDog#1]
The toggle doesn't work in any other mode other than desktop.

**Comment by munnokd** [comment]
Can I work on this issue?

**Comment by Shalini469717** [comment]
yeah sure

**Comment by munnokd** [comment]
Please assign this issue to me.

**Comment by munnokd** [comment]
@Shalini469717 I created pr for it.
If any help is wanted so please feel free to ask me.
